network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      addresses:
        - IPADDR/MASK
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4]
      routes:
        - to: default
          via: GATEWAYADDR


