---
custom:
    sql:
        init:
            location:
                # schema: classpath:/spring-db-init
                schema: file:${custom.project.location.database}/init/script-based
            schema-files: &schema-files
                - ${custom.sql.init.location.schema}/schema-postgresql-01.sql

spring:
    config:
        activate:
            on-profile:
                - db-schema-gen-sb
    sql:
        init:
            # Platform to use in the default schema or data script locations, schema-${platform}.sql and data-${platform}.sql. Not needed here.
            # platform: postgresql
            # To enable 'always initialize' for script-based DataSource initialization using 'schema.sql' and 'data.sql'. Default: never
            mode: always
            schema-locations: *schema-files
    jpa:
        # If you want script-based DataSource initialization to be able to build upon the schema creation performed by Hibernate, e.g. 'data.sql' to run after schema/relation creation
        defer-datasource-initialization: true