#!/bin/sh

# curDir="$(pwd)/configurer/genericDiffAndMergeToolConfigurer"
# curDir="$HOME/MyTools/Linux_Tools/Dev_tools_setup_scripts/git/configurer/genericDiffAndMergeToolConfigurer"
if [ -L $(which extDiff) ]; then
    curDir="$(dirname "$(tracelink extDiff)")"
else
    curDir="$(pwd)/configurer/genericDiffAndMergeToolConfigurer"
fi

$curDir/generic_tool $*