#!/bin/bash

if [ -L $(which extDiff) ]; then
    curDir="$(dirname "$(tracelink extDiff)")"
else
    curDir="$(pwd)/configurer/genericDiffAndMergeToolConfigurer"
fi

[[ $1 == "--help" ]] && ( cat $curDir/setgittool.help )
[[ $1 != "--help" ]] && ( tool=$1; sudo sed -i "s/selected:\(.*\)/selected:"$tool"/" $curDir/.tools )